# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  purty = nodeEnv.buildNodePackage {
    name = "purty";
    packageName = "purty";
    version = "7.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/purty/-/purty-7.0.0.tgz";
      sha512 = "gHHghPEjRY39GUJ8KnOMRfPArJILGCXwEhX6BmEdNiLgZuCjLLBLyawGiKFjYMfy8H5Dsk5NbgwIGslrPrernA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "PureScript pretty printer";
      homepage = "https://gitlab.com/joneshf/purty#README";
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
