# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  purty = nodeEnv.buildNodePackage {
    name = "purty";
    packageName = "purty";
    version = "6.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/purty/-/purty-6.2.0.tgz";
      sha512 = "JfT8kJHSyxuOFQtRiH2x55SiPxXZsSdedQlZap8JehQ7KzB49B5C9cWwVybtSB36BdADQcxPvtw8D52z4EPnBw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "PureScript pretty printer";
      homepage = "https://gitlab.com/joneshf/purty#README";
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}